name: dc-nextcloud

services:
  nc-postgresql:
    image: "postgres:16"
    restart: no
    container_name: "nc-postgresql"
    environment:
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
      POSTGRES_DB: "nextcloud"
    volumes:
      - ./nc-postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nc-proxy-network

  nc-redis:
    image: redis:7
    restart: no
    container_name: "nc-redis"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - nc-proxy-network

  nc-onlyoffice-document-server:
    image: onlyoffice/documentserver:8.1
    restart: no
    container_name: "nc-onlyoffice-document-server"
    volumes:
      - ./nc-onlyoffice/data:/var/www/onlyoffice/Data
      - ./nc-onlyoffice/logs:/var/log/onlyoffice
      - ./nc-onlyoffice/lib:/var/lib/onlyoffice
      - ./nc-onlyoffice/db:/var/lib/postgresql
    environment:
      - REDIS_SERVER_HOST=nc-redis
      - JWT_SECRET=nc_jwt_secret
    expose:
      - 80
    networks:
      - nc-proxy-network
    depends_on:
      - nc-redis

  nc-nextcloud:
    image: nextcloud:29
    restart: no
    container_name: "nc-nextcloud"
    ports:
      - 8080:80
    volumes:
      - ./nc-nextcloud/html:/var/www/html
      - ./nc-nextcloud/apps:/var/www/html/custom_apps
      - ./nc-nextcloud/config:/var/www/html/config
      - ./nc-nextcloud/data:/var/www/html/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=nc-postgresql
      - REDIS_HOST=nc-redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
    networks:
      - nc-proxy-network
    depends_on:
      - nc-redis
      - nc-postgresql

  nc-nginx:
    image: nginx:1.27
    restart: no
    container_name: "nc-nginx"
    ports:
      - 80:80
    volumes:
      - ./nc-nginx/config:/etc/nginx/conf.d
    networks:
      - nc-proxy-network

networks:
  nc-proxy-network:
    external:
      name: nc-nginx
