name: dc-nextcloud

volumes:
  nc-postgres-volume:
    driver: local
  nc-nextcloud-volume:
    driver: local

services:
  nc-postgresql:
    image: "postgres:18"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
      POSTGRES_DB: "nextcloud"
    volumes:
      - nc-postgres-volume:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      - nc-proxy-network

  nc-redis:
    image: redis:8
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    expose:
      - 6379
    networks:
      - nc-proxy-network

  nc-onlyoffice-document-server:
    image: onlyoffice/documentserver:9.4
    restart: unless-stopped
#    volumes:
#      - ./nc-onlyoffice/data:/var/www/onlyoffice/Data
#      - ./nc-onlyoffice/logs:/var/log/onlyoffice
#      - ./nc-onlyoffice/lib:/var/lib/onlyoffice
#      - ./nc-onlyoffice/db:/var/lib/postgresql
    environment:
      REDIS_SERVER_HOST: nc-redis
      JWT_ENABLED: "true"
      JWT_SECRET: nc_jwt_secret
      JWT_HEADER: Authorization
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 80
    networks:
      - nc-proxy-network
    depends_on:
      nc-redis:
        condition: service_healthy

  nc-nextcloud:
    image: nextcloud:32
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - nc-nextcloud-volume:/var/www/html
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_HOST: nc-postgresql
      REDIS_HOST: nc-redis
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - nc-proxy-network
    depends_on:
      nc-redis:
        condition: service_healthy
      nc-postgresql:
        condition: service_healthy

  nc-nginx:
    image: nginx:1.31
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nc-nginx/config:/etc/nginx/conf.d:ro
    networks:
      - nc-proxy-network
    depends_on:
      nc-nextcloud:
        condition: service_healthy
      nc-onlyoffice-document-server:
        condition: service_healthy

networks:
  nc-proxy-network:
    driver: bridge
